/**
 * Represents a single transpiled file with its code and output path.
 *
 * @remarks
 * This interface is used to store the result of a transpilation step,
 * containing the JavaScript code generated by ESBuild (or another transpiler)
 * and the corresponding output file path.
 *
 * @since 1.0.0
 */

export interface TranspileFileInterface {
    /**
     * Transpiled JavaScript code of the file.
     * @since 1.0.0
     */

    code: string;

    /**
     * Absolute or relative output path of the transpiled file.
     * @since 1.0.0
     */

    path: string;
}

/**
 * Represents an array of transpiled files.
 *
 * @remarks
 * Used when multiple files are transpiled in a batch, such as
 * when processing multiple entry points with ESBuild.
 *
 * @see TranspileFileInterface
 * @since 1.0.0
 */

export type TranspileFileType = Array<TranspileFileInterface>;
